apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkle
  labels:
    app: linkle
spec:
  replicas: 2
  selector:
    matchLabels:
      app: linkle
  template:
    metadata:
      labels:
        app: linkle
    spec:
      containers:
        - name: linkle
          image: registry.uniproject.jp/nnn/linkle:3.1.6
          envFrom:
            - secretRef:
                name: env-linkle
                optional: true
          env:
            - name: AUTH_TRUST_HOST
              value: "true"
            - name: AUTH_URL
              value: "https://linkle.unipro-n.com/api/auth"
          ports:
            - containerPort: 3000
              name: default-port
          readinessProbe:
            initialDelaySeconds: 300
            periodSeconds: 20
            httpGet:
              path: /
              port: default-port
              httpHeaders:
                - name: X-k8s-Header
                  value: readiness
          livenessProbe:
            failureThreshold: 3
            timeoutSeconds: 5
            successThreshold: 1
            initialDelaySeconds: 300
            periodSeconds: 20
            httpGet:
              path: /
              port: default-port
              httpHeaders:
                - name: X-k8s-Header
                  value: readiness
      imagePullSecrets:
        - name: internal-harbor
