name: "Next.js Lint"
permissions:
  contents: read
  pull-requests: write
on:
  push:
    branches:
      - main
      - sandbox
      - dev
  pull_request:
    branches:
      - main
      - sandbox
      - dev
  merge_group:
    types: [checks_requested]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install dependencies
        run: npm instal -g bun && bun install
      - name: Lint
        run: bun lint
