name: Vercel RC Deployment
on:
  push:
    tags:
      - 'v*.*.*-rc.*'
  workflow_dispatch:
jobs:
  deployment:
    runs-on: ubuntu-latest
    concurrency: RC
    environment:
      name: RC
      url: ${{ steps.get_release_url.outputs.release_url }}
    steps:
    - uses: yuito-it/GitHub-Vercel-Actions@v1.0.2
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-project: ${{ vars.VERCEL_PROJECT_ALPHA }}
    - name: Set release url
      shell: bash
      id: get_release_url
      run: |
        cat deployment-url.txt
        echo release_url="https://rc.linkle.nnn.uniproject.jp" >> $GITHUB_OUTPUT
      