name: Vercel Production Deployment
on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
jobs:
  checkTag:
    runs-on: ubuntu-latest
    outputs:
      is_production: ${{ steps.check_tag.outputs.is_production }}
    steps:
    - name: Check if tag is production
      id: check_tag
      run: |
        if [[ "${GITHUB_REF#refs/tags/}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "is_production=true" >> $GITHUB_ENV
        else
          echo "is_production=false" >> $GITHUB_ENV
  deployment:
    needs: checkTag
    if: needs.checkTag.outputs.is_production == 'true'
    runs-on: ubuntu-latest
    concurrency: Production
    environment:
      name: Production
      url: ${{ steps.get_release_url.outputs.release_url }}
    steps:
    - uses: yuito-it/GitHub-Vercel-Actions@v1.0.2
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-project: ${{ vars.VERCEL_PROJECT }}
    - name: Set release url
      shell: bash
      id: get_release_url
      run: |
        cat deployment-url.txt
        echo release_url="https://linkle.nnn.uniproject.jp" >> $GITHUB_OUTPUT
